### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by goodmind** [goodmind/telegram.link#1]
I think that this is great project, but it seems to be in stalled state. I don't dived deep in code so I think it would be hard to understand some things. 

**If anyone wants to help me PRs are welcome!**

# Goals
- [x] Remove requirish (implicit)
- [ ] Migrate to ESLint
- [ ] JSDoc types
- [x] Drop 0.10 support
- [ ] Fix methods
- [x] Update TL Schema and API Layer
- [x] Review pull requests (add labels etc)
  - [ ] Merge all pull requests from original project
- [ ] Monorepo (?)

## Repos
- [ ] [goodmind/telegram-tl-node](https://github.com/goodmind/telegram-tl-node)
- [ ] [goodmind/telegram-mt-node](https://github.com/goodmind/telegram-mt-node)
- [ ] [goodmind/telegram.link](https://github.com/goodmind/telegram.link)

**Comment by goodmind** [comment]
So I stuck with updating to new TL schema (implementing flags)

**Comment by goodmind** [comment]
Got `INPUT_FETCH_ERROR` so i don't know how to fix it sorry

**Comment by goodmind** [comment]
Maybe I should port Telethon?

**Comment by jploh** [comment]
I'm only interested in telegram-mt-node. How much work do you think is needed to get it up to speed?

**Comment by goodmind** [comment]
I don't know really I stuck with updating to recent tl schema

**Comment by goodmind** [comment]
I think that this project will have some break, because I can't figure out what's wrong with flag serializing and recent schema

**Comment by goodmind** [comment]
if someone wants to help  i will really appreciate it

**Comment by goodmind** [comment]
Checkout working version! (at least I can login!)

/cc @jploh

**Comment by goodmind** [comment]
@jploh And what's wrong with telegram-mt-node? I am just updated layer version to 57 and it works
